/**
 * POST /api/cloudinary-sign
 * Body: { vehicleId: string }
 *
 * Returns a short-lived signature the browser can use to upload ONE image
 * directly to Cloudinary, scoped to a folder for that vehicle. The
 * CLOUDINARY_API_SECRET never leaves this function — only the signature
 * (a one-way hash valid for these exact parameters) is sent back.
 *
 * Folder layout on Cloudinary:
 *   manchester-auto-cars/vehicles/<vehicleId>/<auto-generated-id>
 */
const { sendJson, methodNotAllowed, readJsonBody, checkEnv, isUrlSafeId, cloudinarySignature } = require("./_util");

module.exports = async (req, res) => {
  if (req.method !== "POST") return methodNotAllowed(res, "POST");

  const env = checkEnv(["CLOUDINARY_CLOUD_NAME", "CLOUDINARY_API_KEY", "CLOUDINARY_API_SECRET"]);
  if (!env.ok) {
    return sendJson(res, 500, {
      error: `Cloudinary is not configured. Missing environment variable(s): ${env.missing.join(", ")}. Add them in Vercel → Project Settings → Environment Variables.`
    });
  }

  let body;
  try { body = await readJsonBody(req); }
  catch (e) { return sendJson(res, 400, { error: e.message }); }

  const vehicleId = body.vehicleId;
  if (!isUrlSafeId(vehicleId)) {
    return sendJson(res, 400, { error: "vehicleId must be a URL-safe id (lowercase letters, digits, hyphens)." });
  }

  const { CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET } = env.values;

  const timestamp = Math.floor(Date.now() / 1000);
  const folder = `manchester-auto-cars/vehicles/${vehicleId}`;
  // Signed so the client cannot swap in a different format list.
  const allowed_formats = "jpg,jpeg,png,webp";

  const signature = cloudinarySignature({ allowed_formats, folder, timestamp }, CLOUDINARY_API_SECRET);

  sendJson(res, 200, {
    cloudName: CLOUDINARY_CLOUD_NAME,
    apiKey: CLOUDINARY_API_KEY, // Cloudinary's API key is not secret; only the API secret is.
    timestamp,
    folder,
    allowedFormats: allowed_formats,
    signature,
    uploadUrl: `https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD_NAME}/image/upload`
  });
};
